<div class="liquido-container">
    <h1>Liquido Pagamentos</h1>
    <?php
    $payin_method_name = $this->getCardPayInMethodName();
    ?>
    <h2>Pagar com <?php echo $payin_method_name ?></h2>

    <form id="credit-card-customer-form" data-mage-init='{"validation": {}}' class="form" action="<?php echo $this->getUrl('checkout/liquidobrl/creditcard', ['_secure' => true]); ?>" method="post">
        <fieldset class="fieldset">
            <legend class="legend"><span><?php echo __('Dados do Cartão') ?></span></legend><br>
            <div class="field required">
                <label for="card-number" class="label"><span><?php echo __('Número') ?></span></label>
                <div class="control">
                    <input type="number" name="card-number" id="card-number" value="" title="<?php echo __('Número') ?>" class="minimum-length-16 maximum-length-16" data-validate="{required:true, 'validate-length':true}">
                </div>
            </div>
            <div class="field required">
                <label for="card-name" class="label"><span><?php echo __('Nome Completo') ?></span></label>
                <div class="control">
                    <input type="text" name="card-name" id="card-name" value="" title="<?php echo __('Nome Completo') ?>" data-validate="{required:true}">
                </div>
            </div>
            <div class="field required">
                <label for="card-date" class="label"><span><?php echo __('Mês / Ano') ?></span></label>
                <div class="control">
                    <input type="text" name="card-date" id="card-date" value="" title="<?php echo __('Mês / Ano') ?>" class="minimum-length-7 maximum-length-7" data-validate="{required:true, 'pattern':'(0[1-9]|10|11|12)/20[0-9]{2}$', 'validate-length':true}">
                </div>
            </div>
            <div class="field required">
                <label for="card-cvv" class="label"><span><?php echo __('CVV') ?></span></label>
                <div class="control">
                    <input type="number" name="card-cvv" id="card-cvv" value="" title="<?php echo __('CVV') ?>" class="minimum-length-3 maximum-length-4" data-validate="{required:true, 'validate-length':true}">
                </div>
            </div>
            <div class="field required">
                <label for="card-installments" class="label"><span><?php echo __('Número de Parcelas') ?></span></label>
                <div class="control">
                    <select name="card-installments" id="card-installments">
                        <?php for ($i = 1; $i <= 12; $i++) :
                            $installments = ($i == 1) ? 'Parcela' : 'Parcelas';
                            $orderTotal = $this->getOrderTotal() / 100;
                            $installmentRound = round($orderTotal / $i, 2);
                            $installmentValue = number_format($installmentRound, 2, ',', '.');
                            $optionInfo = $i . "x de R$ " . $installmentValue; ?>
                            <option value="<?php echo $i ?>"><?php echo $optionInfo ?></option>
                        <?php endfor; ?>
                    </select>
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" id="credit-card-submit-button" class="action submit primary" title="<?php echo __('Pagar') ?>"><span><?php echo __('Pagar') ?></span></button>
            </div>
        </div>
    </form>
</div>